### PR TITLE
Write and read tests

### PR DESCRIPTION
**Pull request by FMota0**
#3 #4

### CODE REVIEW

**Comment by FMota0** [comment]
This pull request **introduces 2 alerts** and **fixes 1** when merging 2bfca899c881f26705846fc5ff029f5d495d9574 into d3eb54b97289d01f56be45b0bd3bf7c3a9ade024 - [view on LGTM.com](https://lgtm.com/projects/g/UpSolv-it/C2LI/rev/pr-06206df4db5c01c0c9b052cb2621ae22a3c59b05)

**new alerts:**

* 2 for Unused variable, import, function or class

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Review by arimateia98 — APPROVED** [review]
Good job.

**Comment by FMota0** [comment]
This pull request **introduces 2 alerts** and **fixes 1** when merging ae8c151723deb9dba5647f4c8bf36d1299eb9338 into d3eb54b97289d01f56be45b0bd3bf7c3a9ade024 - [view on LGTM.com](https://lgtm.com/projects/g/UpSolv-it/C2LI/rev/pr-2aa74d3a70b5675dfe20d14610eed42ceec6f4ce)

**new alerts:**

* 2 for Unused variable, import, function or class

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by FMota0** [comment]
#3 #4

**Comment by FMota0** [comment]
This pull request **introduces 2 alerts** and **fixes 1** when merging 05034e12f169c25be23c3515b4e667c721fd5ea2 into d3eb54b97289d01f56be45b0bd3bf7c3a9ade024 - [view on LGTM.com](https://lgtm.com/projects/g/UpSolv-it/C2LI/rev/pr-7f23d42f46fac637afdc877ca3a82b0debe9540d)

**new alerts:**

* 2 for Unused variable, import, function or class

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by FMota0** [comment]
This pull request **introduces 2 alerts** and **fixes 1** when merging 6044e8fedcb250adb02ff01c17eb9b6e81a7fbb1 into d3eb54b97289d01f56be45b0bd3bf7c3a9ade024 - [view on LGTM.com](https://lgtm.com/projects/g/UpSolv-it/C2LI/rev/pr-ecae87fb27eecf1c45adc612a0fce9c4f7ed9faf)

**new alerts:**

* 2 for Unused variable, import, function or class

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
